// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggtaapqowlmjtbqgwfvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdndGFhcHFvd2xtanRicWd3ZnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDQzNTYsImV4cCI6MjA3MTc4MDM1Nn0.65Ck9dnN1h210IL2vx66fqZBUEWXedm6a8iQiMEWXZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});